config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks'}

    root "home#index" #Calls index method of home controller, then displays index view for home
    get 'home/about' #Creates a new route called "home_about"
    get 'home/terms_of_service'
    get 'home/privacy_policy'
    get 'home/contact'
    get 'home/faq'
    get 'home/sitemap'

    get 'personal_home/index'
    get '/personal_home/edit'=> 'users#edit'
    
    get 'ratings/new'
    # get '/login' => 'sessions#new'
    # post '/login' => 'sessions#create' 
    # delete '/logout' => 'sessions#destroy'
    # Add resource to get the standard RESTful actions for sessions
    #get 'sessions/new'

    resources :users
    resources :people
    resources :transactions
    resources :ratings

    get '/upload' => 'items#new'
    get '/user_items' => 'items#user_items'
    get '/search' => 'items#search'
    get '/remove_item/:id' => 'items#remove', as: 'remove_item'
    get '/borrow_item/:id' => 'items#borrow', as: 'borrow_item'
    resources :items

    #Friends part
    resources :friends do
      get :manage, on: :collection #on member requires ID, on collection doesn't
    end
    get '/accept_friend/:id' => 'friends#accept', as: 'accept_friend'
    get '/reject_friend/:id' => 'friends#reject', as: 'reject_friend'
    get '/acceptd_friend/:id' => 'friends#acceptd', as: 'acceptd_friend'
    get '/rejectd_friend/:id' => 'friends#rejectd', as: 'rejectd_friend'
    get '/search_friend' => 'friends#search', as: 'search_friend'
    get '/sendf_friend/:id' => 'friends#sendf', as: 'sendf_friend'
    get '/sendfd_friend/:id' => 'friends#sendfd', as: 'sendfd_friend'
    get '/remf_friend/:id' => 'friends#remf', as: 'remf_friend'
    get '/remfd_friend/:id' => 'friends#remfd', as: 'remfd_friend'
    get '/remr_friend/:id' => 'friends#remr', as: 'remr_friend'
    get '/remrd_friend/:id' => 'friends#remrd', as: 'remrd_friend'
    get '/ablock_friend/:id' => 'friends#ablock', as: 'ablock_friend'
    get '/ablockd_friend/:id' => 'friends#ablockd', as: 'ablockd_friend'
    get '/rblock_friend/:id' => 'friends#rblock', as: 'rblock_friend'

    #Notifications part
    get '/mall_phome' => 'personal_home#mall', as: 'mall_phome'
    get '/mone_phome/:id' => 'personal_home#mone', as: 'mone_phome'

end

app/models/person.rb
class Person < ApplicationRecord

    belongs_to :user
    has_many :items, dependent: :destroy

    validates :username,:presence => true, :format => {:with => /\A[0-9\w_]{4,32}\z/, message: "only allows letters or numbers and underscore 4-32 characters long."}, :uniqueness => true
    validates :firstname,:presence => true
    validates :lastname, :presence => true
    validates :telephone,:presence => true, :format => {:with => /\A(1-)?\d{3}-\d{3}-\d{4}\z/ , message: "must be of form XXX-XXX-XXXX or X-XXX-XXX-XXXX."}
    validates :country, :presence => true
    validates :state, :presence => true
    validates :city, :presence => true
    validates :address,:presence => true
    validates :addressno,:presence => true, numericality: { only_integer: true }

    geocoded_by :location
    after_validation :geocode

    reverse_geocoded_by :lat, :lon
    after_validation :reverse_geocode

    def location
        [addressno, address, city, state, country].compact.join(', ')
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

    skip_before_action :require_login

    before_action :check_blocked, only:[:show]

    def new
        @person = Person.new
    end

    def create
        @person = Person.new(people_params)
        @person.user_id = current_user.id

        if @person.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
        @person = Person.find_by_user_id(current_user.id);
    end

    def show
        @person = Person.find_by_id(params[:id]);
        @is_current_user = true
        @is_current_user_friend = true
        @has_requested = false
        @has_received = false
        @friend = Friend.new

        if current_user.id != Person.find_by_id(params[:id]).user_id
            @is_current_user = false
            _friend1 = Friend.where(["user_from_id = ? and user_to_id = ? and has_accepted = true",current_user.id,@person.user_id]).first
            _friend2 = Friend.where(["user_to_id = ? and user_from_id = ? and has_accepted = true",current_user.id,@person.user_id]).first
            if _friend1.blank? and _friend2.blank?
                @is_current_user_friend = false
                  _req1 = Friend.where(["user_from_id = ? and user_to_id = ? and has_accepted = false",current_user.id,@person.user_id]).first
                  _req2 = Friend.where(["user_to_id = ? and user_from_id = ? and has_accepted = false",current_user.id,@person.user_id]).first
                  if _req1.blank? and _req2.blank?
                    @has_requested = false
                    @has_received = false
                  elsif _req1.blank?
                    @has_received = true
                    @friend = _req2
                  else
                    @has_requested = true
                    @friend = _req1
                  end
            elsif _friend1.blank?
                @friend = _friend2
            else
                @friend = _friend1
            end
        end
    end

    def update
        @person = Person.find_by_user_id(current_user.id);
        @person.update(people_params)
        redirect_to personal_home_index_path
    end

    private

        def people_params
            params.require(:person).permit(:username, :firstname, :lastname, :telephone, :country, :state, :city, :address, :addressno, :imgurl)
        end

        def check_blocked
            _check1 = Block.where(["block_from_id = ? and block_to_id = ?", current_user.id, params[:id]])
            _check2 = Block.where(["block_to_id = ? and block_from_id = ?", current_user.id, params[:id]])
            if _check1.blank? and _check2.blank? then
                true
            else
                redirect_to root_path
            end
        end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_error.html.erb
<% if @person.errors.any? %>
    <div id="error_explanation">
        <p>
            <%= pluralize(@person.errors.count, "error") %> prohibited this person from being created:
        </p>

        <ul>
            <% @person.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/people/edit.html.erb
<br>
<br>
<br>

<%= render 'error' %>

<div class='container-fluid mt-5'>
    <div class='row justify-content-center'>
        <div class='col-sm-5'>
            <div class='card'>
                <div class='card-body'>

                    <h1>Edit Your Profile</h1>

                    <%= form_with(model: @person, local: true) do |form| %>

                        <div class='form-group'>
                            <%= form.label :username, "Username (What other users will see you as)" %><br>
                            <%= form.text_field :username, :class => 'form-control' %>
                        </div>
              
                        <div class='form-group'>
                            <%= form.label :firstname, "First Name" %><br>
                            <%= form.text_field :firstname, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :lastname, "Last Name" %><br>
                            <%= form.text_field :lastname, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :telephone, "Telephone #" %><br>
                            <%= form.text_field :telephone, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :country, "Country" %><br>
                            <%= form.text_field :country, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :state, "State/Province" %><br>
                            <%= form.text_field :state, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :city, "City" %><br>
                            <%= form.text_field :city, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :address, "Street Name" %><br>
                            <%= form.text_field :address, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :addressno, "Street Number" %><br>
                            <%= form.text_field :addressno, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :imgurl, "Image URL" %><br>
                            <%= form.text_field :imgurl, :class => 'form-control' %>
                        </div>

                        <div>
                            <%= form.submit 'Submit', :class => 'btn btn-blue' %>
                        </div>

                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/people/new.html.erb
<%= render 'error' %>

<div class='container-fluid mt-5'>
    <div class='row justify-content-center'>
        <div class='col-sm-5'>
            <div class='card'>
                <div class='card-body'>

                    <h1>Please Configure Your Profile</h1>

                    <%= form_with scope: :person, url: people_path, local: true do |form| %>

                        <div class='form-group'>
                            <%= form.label :username, "Username (How others will find you)" %><br>
                            <%= form.text_field :username, :class => 'form-control' %>
                        </div>
              
                        <div class='form-group'>
                            <%= form.label :firstname, "First Name" %><br>
                            <%= form.text_field :firstname, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :lastname, "Last Name" %><br>
                            <%= form.text_field :lastname, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :telephone, "Telephone #" %><br>
                            <em>(Must be of form XXX-XXX-XXXX or X-XXX-XXX-XXXX)</em>
                            <%= form.text_field :telephone, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :country, "Country" %><br>
                            <%= form.text_field :country, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :state, "State/Province" %><br>
                            <%= form.text_field :state, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :city, "City" %><br>
                            <%= form.text_field :city, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :address, "Street Name" %><br>
                            <%= form.text_field :address, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :addressno, "Street Number" %><br>
                            <%= form.text_field :addressno, :class => 'form-control' %>
                        </div>

                        <div class='form-group'>
                            <%= form.label :imgurl, "Image URL" %><br>
                            <%= form.text_field :imgurl, :class => 'form-control' %>
                        </div>

                        <div>
                            <%= form.submit 'Submit', :class => 'btn btn-blue' %>
                        </div>

                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/people/show.html.erb
<br>
<br>
<br>

<div class='container-fluid mt-3'>
  <%= link_to "Go Back Home", root_path %>
    <div class='row pt-4 justify-content-center'>
        <div class='col-4-sm pl-3 pr-3'>
            <div class="card border-0">
                <div class="card-body">

	            <div class='row justify-content-center'>
	        	<div class="col">

                            <h1>
                                <%= @person.username %>'s Profile
                            </h1>
	        
                            <p>
                                <strong>First Name:</strong>
                                <%= @person.firstname %>
                            </p>

                            <p>
                                <strong>Last Name:</strong>
                                <%= @person.lastname %>
                            </p>

                            <% if @is_current_user %>

                                <p>
    			            <strong>Street Address:</strong>
                                    <%= @person.address %>
                                </p>

                                <p>
                                    <strong>City:</strong>
                                    <%= @person.city %>
                                </p>

                                <p>
                                    <strong>Country:</strong>
                                    <%= @person.country %>
                                </p>

                            <% else %>

                                <p>
                                    <strong>Email:</strong>
                                    <%= User.find_by_id(@person.user_id).email %>
                                </p>

                            <% end %>

                            <p>
                                <strong>Telephone:</strong>
                                <%= @person.telephone %>
                            </p>

                        </div>
                    </div>

                    <% if @is_current_user %>
                        <%= link_to 'Edit Profile', edit_person_path %>
                    <% elsif @is_current_user_friend %>
                        <%= link_to "Remove Friend", remfd_friend_path(@friend.id) %>
                    <% elsif @has_requested %>
                        <%= link_to "Remove Request", remrd_friend_path(@friend.id) %>
                    <% elsif @has_received %>
                        <%= link_to "Accept Friend Request", acceptd_friend_path(@friend.id) %>&nbsp|
                        <%= link_to "Reject Friend Request", rejectd_friend_path(@friend.id) %>
                    <% else %>
                        <%= link_to "Send Friend Request", sendfd_friend_path(@person.user_id) %>&nbsp|
                        <%= link_to "Block User", ablockd_friend_path(@person.user_id) %>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>