config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks'}

    root "home#index" #Calls index method of home controller, then displays index view for home
    get 'home/about' #Creates a new route called "home_about"
    get 'home/terms_of_service'
    get 'home/privacy_policy'
    get 'home/contact'
    get 'home/faq'
    get 'home/sitemap'

    get 'personal_home/index'
    get '/personal_home/edit'=> 'users#edit'
    
    get 'ratings/new'
    # get '/login' => 'sessions#new'
    # post '/login' => 'sessions#create' 
    # delete '/logout' => 'sessions#destroy'
    # Add resource to get the standard RESTful actions for sessions
    #get 'sessions/new'

    resources :users
    resources :people
    resources :transactions
    resources :ratings

    get '/upload' => 'items#new'
    get '/user_items' => 'items#user_items'
    get '/search' => 'items#search'
    get '/remove_item/:id' => 'items#remove', as: 'remove_item'
    get '/borrow_item/:id' => 'items#borrow', as: 'borrow_item'
    resources :items

    #Friends part
    resources :friends do
      get :manage, on: :collection #on member requires ID, on collection doesn't
    end
    get '/accept_friend/:id' => 'friends#accept', as: 'accept_friend'
    get '/reject_friend/:id' => 'friends#reject', as: 'reject_friend'
    get '/acceptd_friend/:id' => 'friends#acceptd', as: 'acceptd_friend'
    get '/rejectd_friend/:id' => 'friends#rejectd', as: 'rejectd_friend'
    get '/search_friend' => 'friends#search', as: 'search_friend'
    get '/sendf_friend/:id' => 'friends#sendf', as: 'sendf_friend'
    get '/sendfd_friend/:id' => 'friends#sendfd', as: 'sendfd_friend'
    get '/remf_friend/:id' => 'friends#remf', as: 'remf_friend'
    get '/remfd_friend/:id' => 'friends#remfd', as: 'remfd_friend'
    get '/remr_friend/:id' => 'friends#remr', as: 'remr_friend'
    get '/remrd_friend/:id' => 'friends#remrd', as: 'remrd_friend'
    get '/ablock_friend/:id' => 'friends#ablock', as: 'ablock_friend'
    get '/ablockd_friend/:id' => 'friends#ablockd', as: 'ablockd_friend'
    get '/rblock_friend/:id' => 'friends#rblock', as: 'rblock_friend'

    #Notifications part
    get '/mall_phome' => 'personal_home#mall', as: 'mall_phome'
    get '/mone_phome/:id' => 'personal_home#mone', as: 'mone_phome'

end

app/controllers/personal_home_controller.rb
class PersonalHomeController < ApplicationController

    def index
        @user_id = current_user.id
        @user = User.find(@user_id)
        @person = @user.person
        
        #Get the lending transactions
        @lend_items = Item.where(["person_id = ? AND is_available = ?", @user_id, false])
        ids = Array.new
        @lend_items.each do |x|
            ids.push(x.id)
        end
        @lend = Transaction.where(item_id: ids)
        @lend = @lend.where.not(status: 'closed')
        @lend = @lend.where.not(status: 'rejected')
        @lend = @lend.where.not(status: 'force closed')
        #Get the borrowing transactions
        @borrow = Transaction.where(["user_id = ?",@user_id])
        @borrow = @borrow.where.not(status: 'closed')
        @borrow = @borrow.where.not(status: 'rejected')
        @borrow = @borrow.where.not(status: 'force closed')
        @your_ratings = Rating.where(["ratee = ?", @user_id])
        @total_score = 0
    
        @your_ratings.each do |t|
            @total_score = @total_score + t.score
        end

        @rating_average = (@total_score.to_f / @your_ratings.size).round(2)
        
        #awaitfriends contains all friends requests the user has received
        @awaitfriends = ActiveRecord::Base.connection.exec_query("select a.id, b.username, b.user_id, date(a.created_at) as drecv from friends a, people b where a.user_to_id = #{current_user.id} and a.has_accepted = false and b.user_id = a.user_from_id")

        @notifications = Notification.where(["user_to_id = ? AND has_seen = false", @user_id])
                                                
    end                                
           
    def edit
        @user = User.find(session[:user_id])
    end

    def update 
        @user = User.find(params[:id])
        if @user.update_attributes(userparams)

        else
            render 'edit'
        end

    end

    def mone
      @notice = Notification.find(params[:id])
      if @notice.update(has_seen: true)
        redirect_to personal_home_index_path
      else
        redirect_to personal_home_index_path, danger: "An error ocurred"
      end
    end

    def mall
      @notice = Notification.where(["user_to_id = ? AND has_seen = false", current_user.id])
      if @notice.update_all(has_seen: true)
        redirect_to personal_home_index_path
      else
        redirect_to personal_home_index_path, danger: "An error ocurred"
      end
    end

    def rating
        @rating = Rating.new
    end

end

app/helpers/personal_home_helper.rb
module PersonalHomeHelper
end

app/views/personal_home/edit.html.erb
<%= link_to "Home", root_path%>
<%= link_to "About Me", home_about_path%>
<%= link_to "Personal Home", personal_home_index_path%>
<%= link_to "Log Out", logout_path, method: :delete%>

<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :username %>
            <%= f.text_field :username, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Save changes", class: "btn btn-primary" %>

        <% end %>

    </div>
</div>

app/views/personal_home/index.html.erb
<%= render "layouts/single_header" %>

<div class="w3-light-grey" style="margin-top:77px; margin-bottom: 16px; max-width: 1400px;">
    <div class="w3-row-padding">
        <div class="w3-third">
            <div class="w3-card-4">
                <div class="w3-display-container">
                    <% if @user.person.imgurl == nil || "" %>
                        <%= image_tag("/assets/default_profile.jpg", size:"350x233", style:'width: 100%;') %>
                    <% else %>
                        <%= image_tag(@user.person.imgurl, size:"350x233", style:'width: 100%;') %>
                    <% end %>
                </div>

                <h1 class="w3-padding-16">Welcome <%= @person.username %></h1>
                <p><i class="fa fa-user-circle fa-fw w3-margin-right w3-large w3-text-teal"></i><%=@person.firstname%> <%=@person.lastname%></p>
                <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i><%=@user.email%></p>
                <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i><%=@person.telephone%></p>
                <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i><%=@person.address%></p>
              <p> <%= link_to "Edit Profile", edit_person_path(@person)%></p>
              <p> <%= link_to "Change Password/Delete Account", edit_user_registration_path%></p>
            </div>
            <br>
            <div class="w3-card-4">

                <h1 class="w3-padding-16">Notifications</h1>
                <% unless @notifications.blank? %>
                <%= link_to "Mark all as seen", mall_phome_path %><br>
                <table>
                  <tr>
                    <th>All your notifications</th>
                    <th>Seen</th>
                  </tr>
                  <% @notifications.each do |f| %>
                    <tr>
                      <td><%= f.message %></td>
                      <td><%= link_to "OK", mone_phome_path(f.id) %></td>
                    </tr>
                  <% end %>
                </table><br><br>
                <% else %>
                  <br><i>There are no notifications to display.</i>
                  <br><br>
                <% end %>

            </div>
        </div>

        <div class="w3-twothird">
            <div class="w3-card" style="margin-bottom:16px !important; min-height: 300">
                <h2 class="w3-padding-16"><i class="fa fa-fw fa-sign-out w3-margin-right w3-text-teal"></i>Recent Lending</h2>
                <%= link_to "Post New Item", new_item_path %>
                <% if @lend.size != 0 %>
                    <table>
                        <tr>
                          <th>Transaction ID</th>
                          <th>Item Name</th>
                          <th>Borrower</th>
                          <th>Start Date</th>
                          <th>Due Date</th>
                          <th>Deposit</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                     
                        <% @lend.each do |transaction| %>
                          <tr>
                            <td><%= transaction.id %></td>
                            <td><%= transaction.item.name %></td>
                            <td><%= transaction.user.person.username %></td>
                            <td><%= transaction.start_date %></td>
                            <td><%= transaction.due_date %></td>
                            <td><%= transaction.deposit %></td>
                            <td><%= transaction.status %></td>
                            <% if transaction.status == 'pending' %>
                              <td><%= link_to 'Accept', transaction_path(transaction, status: 'accepted'),
                                              method: :patch,
                                              data: { confirm: 'Are you sure to accept this transaction?' }
                              %> | <%= link_to 'Reject', transaction_path(transaction, status: 'rejected'),
                                              method: :patch,
                                              data: { confirm: 'Are you sure to reject this transaction?' }
                              %></td>
                            <% end %>
                            <% if transaction.status == 'accepted' %>
                              <td><%= link_to 'Detail', item_path(transaction.item.id) %></td>
                            <% end %>
                            <% if transaction.status == 'returned' %>
                              <td><%= link_to 'Close', transaction_path(transaction, status: 'closed'),
                                              method: :patch,
                                              data: { confirm: 'Are you sure to close this transaction?' }
                              %></td>
                            <% end %>
                            <% if transaction.status == 'closed' %>
                              <td><%= link_to 'Detail', item_path(transaction.item.id) %></td>
                            <% end %>
                          </tr>
                        <%end%>
                    </table>
                <%else%>
                      <br><i>You didn't lend anything recently.</i>
                      <br><br>
                <%end%>
            </div>

            <div class="w3-card" style="margin-bottom:16px !important; min-height: 300">
                <h2 class="w3-padding-16"><i class="fa fa-fw fa-sign-in w3-margin-right w3-text-teal"></i>Recent Borrowing</h2>
                <%= link_to "Borrow Now", root_path %>
                <% if @borrow.size != 0 %>
                    <table>
                        <tr>
                          <th>Transaction ID</th>
                          <th>Item Name</th>
                          <th>Owner</th>
                          <th>Start Date</th>
                          <th>Due Date</th>
                          <th>Deposit</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                     
                        <% @borrow.each do |transaction| %>
                          <tr>
                            <td><%= transaction.id %></td>
                            <td><%= transaction.item.name %></td>
                            <td><%= transaction.item.person.username %></td>
                            <td><%= transaction.start_date %></td>
                            <td><%= transaction.due_date %></td>
                            <td><%= transaction.deposit %></td>
                            <td><%= transaction.status %></td>
                            <% if transaction.status == 'pending' %>
                              <td><%= link_to 'Detail', item_path(transaction.item.id) %></td>
                            <% end %>
                            <% if transaction.status == 'accepted' %>
                              <td><%= link_to 'Return', transaction_path(transaction, status: 'returned'),
                                              method: :patch,
                                              data: { confirm: 'Are you sure you have returned the item?' }
                              %></td>
                            <% end %>
                            <% if transaction.status == 'returned' %>
                              <td><%= link_to 'Detail', item_path(transaction.item.id) %></td>
                            <% end %>
                            <% if transaction.status == 'closed' %>
                              <td><%= link_to 'Detail', item_path(transaction.item.id) %></td>
                            <% end %>
                          </tr>
                        <%end%>
                    </table>
                <%else%>
                      <br><i>You didn't borrow anything recently.</i>
                      <br><br>
                <%end%>
            </div>
            
            <div class="w3-card">
                <h2 class="w3-padding-16"><i class="fa fa-fw fa-users w3-margin-right w3-text-teal"></i>Friend Requests</h2>
                <% unless @awaitfriends.blank? %>
                    <tr><table>
                      <tr>
                        <th>Username</th>
                        <th>Received on</th>
                        <th>Options</th>
                      </tr>
                      <% @awaitfriends.each do |f| %>
                        <tr>
                          <td><%= f["username"] %></td>
                          <td><%= f["drecv"] %></td>
                          <td>
                            <%= link_to "Profile", person_path(f["user_id"]) %>&nbsp|
                            <%= link_to "Accept", acceptd_friend_path(f["id"]) %>&nbsp|
                            <%= link_to "Reject", rejectd_friend_path(f["id"]) %>&nbsp
                          </td>
                        </tr>
                      <% end %>
                    </table></tr>
                    <% else %>
                      <br><i>You currently don't have pending received friend requests</i>
                      <br><br>
                    <% end %>

            </div>
        </div>
    </div>
</div>

<%= render "layouts/footer" %>

<style>
table{
    border: solid 1px;
    width:100%;
}

td{
    border: solid 1px;
    width: auto;
    text-align: center;
}

th{
    border: solid 1px;
    width: auto;
    text-align: center;
}

a{
    color: #f9be37;
}

</style>