config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks'}

    root "home#index" #Calls index method of home controller, then displays index view for home
    get 'home/about' #Creates a new route called "home_about"
    get 'home/terms_of_service'
    get 'home/privacy_policy'
    get 'home/contact'
    get 'home/faq'
    get 'home/sitemap'

    get 'personal_home/index'
    get '/personal_home/edit'=> 'users#edit'
    
    get 'ratings/new'
    # get '/login' => 'sessions#new'
    # post '/login' => 'sessions#create' 
    # delete '/logout' => 'sessions#destroy'
    # Add resource to get the standard RESTful actions for sessions
    #get 'sessions/new'

    resources :users
    resources :people
    resources :transactions
    resources :ratings

    get '/upload' => 'items#new'
    get '/user_items' => 'items#user_items'
    get '/search' => 'items#search'
    get '/remove_item/:id' => 'items#remove', as: 'remove_item'
    get '/borrow_item/:id' => 'items#borrow', as: 'borrow_item'
    resources :items

    #Friends part
    resources :friends do
      get :manage, on: :collection #on member requires ID, on collection doesn't
    end
    get '/accept_friend/:id' => 'friends#accept', as: 'accept_friend'
    get '/reject_friend/:id' => 'friends#reject', as: 'reject_friend'
    get '/acceptd_friend/:id' => 'friends#acceptd', as: 'acceptd_friend'
    get '/rejectd_friend/:id' => 'friends#rejectd', as: 'rejectd_friend'
    get '/search_friend' => 'friends#search', as: 'search_friend'
    get '/sendf_friend/:id' => 'friends#sendf', as: 'sendf_friend'
    get '/sendfd_friend/:id' => 'friends#sendfd', as: 'sendfd_friend'
    get '/remf_friend/:id' => 'friends#remf', as: 'remf_friend'
    get '/remfd_friend/:id' => 'friends#remfd', as: 'remfd_friend'
    get '/remr_friend/:id' => 'friends#remr', as: 'remr_friend'
    get '/remrd_friend/:id' => 'friends#remrd', as: 'remrd_friend'
    get '/ablock_friend/:id' => 'friends#ablock', as: 'ablock_friend'
    get '/ablockd_friend/:id' => 'friends#ablockd', as: 'ablockd_friend'
    get '/rblock_friend/:id' => 'friends#rblock', as: 'rblock_friend'

    #Notifications part
    get '/mall_phome' => 'personal_home#mall', as: 'mall_phome'
    get '/mone_phome/:id' => 'personal_home#mone', as: 'mone_phome'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!
  skip_before_action :require_login

  def index
    if params.has_key?(:token)
      flash.now[:danger] = 'Payment is incomplete, please try again.'
    end
  end
    
  def about #Helps me link_to the about page
  end 

  def show

  end

  def personal_home
  end	

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "About Us"}  %>

<section>
  <br>
  <br>
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section fadeInUp ftco-animated">
        <p>
        <h2> About us</h2>
        Welcome to Lendlord, your number one source for borrowing and lending items in the community. We're dedicated to giving you the very best service, with a focus on dependability, customer service and uniqueness.<br><br>
        Founded in 2018, Lendlord has come a long way from its beginnings in Toronto, Canada. When we first started out, our passion for allowing the community to share, by borrowing and lending, drove us to start this website. We now serve customers all over the world, and are thrilled to bring this website to all the communities.
        </p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/footer" %>

app/views/home/contact.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "Contact "}  %>

<section>
  <br>
  <br>
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section fadeInUp ftco-animated">
        <p>
        <h2>Contact Us</h2>
        <h3>Address:</h3>
        27 King's College Cir, Toronto, ON M5S
        <h3>Phone:</h3>
        <a href="tel://1234567920">+ 416 123 4567</a>
        <h3>Email:</h3>
        <a href="mailto:info@lendlord.com">info@lendlord.com</a>
        </p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/footer" %>

app/views/home/faq.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "FAQ"}  %>

<section>
  <br>
  <br>
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section fadeInUp ftco-animated">
        <p>
        <h2>FAQ</h2><br>
        <h3>Q: Why Lendlord?</h3>

        We provide a platform where everyone in the community can borrow and lend items freely.<br><br>

        <h3>Q: How Lendlord works?</h3>

        Search from an item in the home page, click on it, and procede!.<br><br>

        <h3>Q: What are my deposit payment options?</h3>

        Currently, we only accept debit card through PayPal.<br><br>

        <h3>Q: What happens if I don't return the item?</h3>

        Your deposit will not be returned to you, and will be given to the lender (owner).<br><br>

        <h3>Q: Can I lend or borrow from someone who lives abroad or overseas?</h3>

        Yes, you can!. But keep in mind that you have to cover shipment and taxes costs.<br>

        </p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/footer" %>

app/views/home/index.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "Discover"}  %>

<%= render "layouts/search_bar" %>

<section class="ftco-section bg-light">
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section text-center">
        <h2 class="mb-4">See our latest items</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <a href="/search?utf8=✓&search=bike&location=" class="destination-entry img" style="background-image: url('/assets/bikes.jpg');">
          <div class="text text-center">
            <h3>Bikes</h3>
          </div>
        </a>
      </div>
      <div class="col-md-4">
        <a href="/search?utf8=✓&search=book&location=" class="destination-entry img" style="background-image: url('/assets/books.jpg');">
          <div class="text text-center">
            <h3>Books</h3>
          </div>
        </a>
      </div>
      <div class="col-md-4">
        <a href="/search?utf8=✓&search=supplies&location=" class="destination-entry img" style="background-image: url('/assets/supplies.jpg');">
          <div class="text text-center">
            <h3>Supplies</h3>
          </div>
        </a>
      </div>
    </div>
  </div>
</section>


<%= render "layouts/footer" %>

app/views/home/privacy_policy.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "Privacy Policy"}  %>

<section>
  <br>
  <br>
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section fadeInUp ftco-animated">
        <p>
          <h2>Privacy Policy</h2>

          <p>Effective date: December 01, 2018</p>

          <p>Lendlord operates the https://lendlord.herokuapp.com/ website (the "Service").</p>

          <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

          <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://lendlord.herokuapp.com/</p>

          <h3>Information Collection And Use</h3>

          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

          <h3>Types of Data Collected</h3>

          <h4>Personal Data</h4>

          <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

          <ul>
            <li>Email address</li><li>First name and last name</li><li>Phone number</li><li>Address, State, Province, ZIP/Postal code, City</li><li>Cookies and Usage Data</li>
          </ul>

          <h4>Usage Data</h4>

          <p>We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

          <h4>Tracking & Cookies Data</h4>
          <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
          <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
          <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
          <p>Examples of Cookies we use:</p>
          <ul>
            <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
          </ul>

          <h3>Use of Data</h3>

          <p>Lendlord uses the collected data for various purposes:</p>
          <ul>
            <li>To provide and maintain the Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer care and support</li>
            <li>To provide analysis or valuable information so that we can improve the Service</li>
            <li>To monitor the usage of the Service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>

          <h3>Transfer Of Data</h3>
          <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
          <p>If you are located outside Canada and choose to provide information to us, please note that we transfer the data, including Personal Data, to Canada and process it there.</p>
          <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
          <p>Lendlord will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

          <h3>Disclosure Of Data</h3>

          <h4>Legal Requirements</h4>
          <p>Lendlord may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul>
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Lendlord</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>

          <h3>Security Of Data</h3>
          <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

          <h3>Service Providers</h3>
          <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
          <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>



          <h3>Links To Other Sites</h3>
          <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>


          <h3>Children's Privacy</h3>
          <p>Our Service does not address anyone under the age of 18 ("Children").</p>
          <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>


          <h3>Changes To This Privacy Policy</h3>
          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
          <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>


          <h3>Contact Us</h3>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <ul>
            <li>By email: info@lendlord.com</li>

          </ul>

          </p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/footer" %>

app/views/home/sitemap.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "Our Site Map"}  %>

<section>
  <br>
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section fadeInUp ftco-animated">
        <p>
        <h2>Information</h2>
          <ul>
            <li><%= link_to "Home", root_path, class:"py-1 d-block"%></li>
            <li><%= link_to "About Us", home_about_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Terms of Service", home_terms_of_service_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Privacy Policy", home_privacy_policy_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Contact Us", home_contact_path, class:"py-1 d-block"%></li>
            <li><%= link_to "FAQ", home_faq_path, class:"py-1 d-block"%></li>
          </ul>
        <br><h2>Services</h2>
          <ul>
            <li><%= link_to "User Items", user_items_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Transactions", transactions_path, class:"py-1 d-block"%></li>
          </ul>
        <br><h2>Profile</h2>
          <ul>
            <li><%= link_to "View Profile", personal_home_index_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Edit Profile", edit_person_path(@person), class:"py-1 d-block"%></li>
            <li><%= link_to "Settings", edit_user_registration_path, class:"py-1 d-block"%></li>
          </ul>
        <br><h2>Social</h2>
          <ul>
            <li><%= link_to "Friends", friends_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Search Users", new_friend_path, class:"py-1 d-block"%></li>
            <li><%= link_to "Block lists", manage_friends_path, class:"py-1 d-block"%></li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/footer" %>

app/views/home/terms_of_service.html.erb
<%= render :partial => "layouts/header", :locals => {:title => "Terms Of Service"}  %>

<section>
  <br>
  <br>
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section fadeInUp ftco-animated">
        <p>
        <h2>Terms of Service</h2>
          Please read these terms of service carefully before using Lendlord website operated by us.

        <h3>Conditions of Use</h3>

          We will provide their services to you, which are subject to the conditions stated below in this document. Every time you visit this website, use its services or make a purchase, you accept the following conditions. This is why we urge you to read them carefully.

        <h3>Privacy Policy </h3>

          Before you continue using our website we advise you to read our <%= link_to "Privacy Policy", home_privacy_policy_path%> regarding our user data collection. It will help you better understand our practices.

        <h3>Communications</h3>

          The entire communication with us is electronic. Every time you send us an email or visit our website, you are going to be communicating with us. You hereby consent to receive communications from us. If you subscribe to the news on our website, you are going to receive regular emails from us. We will continue to communicate with you by posting news and notices on our website and by sending you emails. You also agree that all notices, disclosures, agreements and other communications we provide to you electronically meet the legal requirements that such communications be in writing.

        <h3>Applicable Law</h3>

          By visiting this website, you agree that the laws of Canada, without regard to principles of conflict laws, will govern these terms of service, or any dispute of any sort that might come between us and you, or its business partners and associates.

        <h3>Disputes</h3>

          Any dispute related in any way to your visit to this website or to products you purchase from us shall be arbitrated by state or federal court of Canada and you consent to exclusive jurisdiction and venue of such courts.


          We reserve all rights (but not the obligation) to remove and/or edit such content. When you post your content, you grant us non-exclusive, royalty-free and irrevocable right to use, reproduce, publish, modify such content throughout the world in any media.

        <h3>License and Site Access</h3>

          We grant you a limited license to access and make personal use of this website. You are not allowed to download or modify it. This may be done only with written consent from us.

        <h3>User Account</h3>

          If you are an owner of an account on this website, you are solely responsible for maintaining the confidentiality of your private user details (username and password). You are responsible for all activities that occur under your account or password.

          We reserve all rights to terminate accounts, edit or remove content and cancel orders in their sole discretion.</p>
      </div>
    </div>
  </div>
</section>

<%= render "layouts/footer" %>