config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {registrations: 'users/registrations',sessions: 'users/sessions',  omniauth_callbacks: 'users/omniauth_callbacks'}

    root "home#index" #Calls index method of home controller, then displays index view for home
    get 'home/about' #Creates a new route called "home_about"
    get 'home/terms_of_service'
    get 'home/privacy_policy'
    get 'home/contact'
    get 'home/faq'
    get 'home/sitemap'

    get 'personal_home/index'
    get '/personal_home/edit'=> 'users#edit'
    
    get 'ratings/new'
    # get '/login' => 'sessions#new'
    # post '/login' => 'sessions#create' 
    # delete '/logout' => 'sessions#destroy'
    # Add resource to get the standard RESTful actions for sessions
    #get 'sessions/new'

    resources :users
    resources :people
    resources :transactions
    resources :ratings

    get '/upload' => 'items#new'
    get '/user_items' => 'items#user_items'
    get '/search' => 'items#search'
    get '/remove_item/:id' => 'items#remove', as: 'remove_item'
    get '/borrow_item/:id' => 'items#borrow', as: 'borrow_item'
    resources :items

    #Friends part
    resources :friends do
      get :manage, on: :collection #on member requires ID, on collection doesn't
    end
    get '/accept_friend/:id' => 'friends#accept', as: 'accept_friend'
    get '/reject_friend/:id' => 'friends#reject', as: 'reject_friend'
    get '/acceptd_friend/:id' => 'friends#acceptd', as: 'acceptd_friend'
    get '/rejectd_friend/:id' => 'friends#rejectd', as: 'rejectd_friend'
    get '/search_friend' => 'friends#search', as: 'search_friend'
    get '/sendf_friend/:id' => 'friends#sendf', as: 'sendf_friend'
    get '/sendfd_friend/:id' => 'friends#sendfd', as: 'sendfd_friend'
    get '/remf_friend/:id' => 'friends#remf', as: 'remf_friend'
    get '/remfd_friend/:id' => 'friends#remfd', as: 'remfd_friend'
    get '/remr_friend/:id' => 'friends#remr', as: 'remr_friend'
    get '/remrd_friend/:id' => 'friends#remrd', as: 'remrd_friend'
    get '/ablock_friend/:id' => 'friends#ablock', as: 'ablock_friend'
    get '/ablockd_friend/:id' => 'friends#ablockd', as: 'ablockd_friend'
    get '/rblock_friend/:id' => 'friends#rblock', as: 'rblock_friend'

    #Notifications part
    get '/mall_phome' => 'personal_home#mall', as: 'mall_phome'
    get '/mone_phome/:id' => 'personal_home#mone', as: 'mone_phome'

end

app/views/layouts/_footer.html.erb
<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Connect</h2>
          <p>Stay connected with us on our social media pages for more items that you'll love!</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
            <li class="fadeInUp ftco-animated"><a href="https://www.twitter.com/"><span class="icon-twitter"></span></a></li>
            <li class="fadeInUp ftco-animated"><a href="https://www.facebook.com/"><span class="icon-facebook"></span></a></li>
            <li class="fadeInUp ftco-animated"><a href="https://www.instagram.com/"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Information</h2>
          <ul class="list-unstyled">
            <li><%= link_to "About Us", home_about_path, class:"py-2 d-block"%></li>
            <li><%= link_to "Terms of Service", home_terms_of_service_path, class:"py-2 d-block"%></li>
            <li><%= link_to "Privacy Policy", home_privacy_policy_path, class:"py-2 d-block"%></li>
            <li><%= link_to "Contact Us", home_contact_path, class:"py-2 d-block"%></li>
            <li><%= link_to "Site Map", home_sitemap_path, class:"py-2 d-block"%></li>
            <li><%= link_to "FAQ", home_faq_path, class:"py-2 d-block"%></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Map</h2>
          <div class="block-23 mb-3">
            <ul>
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11545.168943821136!2d-79.3956564!3d43.6628917!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8d1d9bb6765a76f7!2sUniversity+of+Toronto+-+St.+George+Campus!5e0!3m2!1sen!2sca!4v1543183750677" width="330" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright @2018 All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <%= link_to "LendLord", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% @person = Person.find_by_user_id(current_user.id) %>

          <li class="nav-item"><%= link_to "Welcome, " + @person.username + "!", personal_home_index_path, class:"nav-link"%></li>
          <li class="nav-item"><%= link_to "My Profile", personal_home_index_path, class:"nav-link"%></li>
          <li class="nav-item"><%= link_to "Friends", friends_path, class:"nav-link"%></li>
          <% if current_user.person.username == "admin" %>
            <li class="nav-item"><%= link_to "User Items", items_path, class:"nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "My Items", user_items_path, class:"nav-link" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "Transactions", transactions_path, class:"nav-link"%></li>
          <li class="nav-item"> <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-link"%></li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%></li>
          <li class="nav-item"><%= link_to "Log In", new_user_session_path, class:"nav-link", id:"login"%></li>
        <% end %>
        <li class="nav-item"><%= link_to "Lend", new_item_path, class:"nav-link"%></li>

      </ul>
    </div>
  </div>
</nav>

<div class="hero-wrap js-fullheight" style="height: 600px !important; background-image: url('/assets/tools.jpg');">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true" style="padding-top: 150px">
      <div class="col-md-9 text-center" data-scrollax=" properties: { translateY: '70%' }">
        <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
          <% if defined?title %>
            <%= title %>
          <% end %>
        </h1>
        <p class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }" >
          <% if defined?subtitle %>
            <%= subtitle %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>
</section>

<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/jquery-migrate-3.0.1.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery.easing.1.3.js"></script>
<script src="/assets/js/jquery.waypoints.min.js"></script>
<script src="/assets/js/jquery.stellar.min.js"></script>
<script src="/assets/js/owl.carousel.min.js"></script>
<script src="/assets/js/jquery.magnific-popup.min.js"></script>
<script src="/assets/js/aos.js"></script>
<script src="/assets/js/jquery.animateNumber.min.js"></script>
<script src="/assets/js/bootstrap-datepicker.js"></script>
<script src="/assets/js/scrollax.min.js"></script>
<script src="/assets/js/google-map.js"></script>
<script src="/assets/js/main.js"></script>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
            <li>
                <%= value %>
            </li>
        </ul>
    </div>
<% end %>

app/views/layouts/_more_items.html.erb
<section class="ftco-section-parallax">
  <div class="parallax-img d-flex align-items-center">
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="col-md-7 text-center heading-section heading-section-white">
          <h2><%= link_to "Find More Items That You'll Love!", root_path, :style => "color: white;" %></h2>
          <div class="row">
            <div class="col-md-4">
              <a href="/search?utf8=✓&search=bike&location=" class="destination-entry img" style="background-image: url('/assets/bikes.jpg');">
                <div class="text text-center">
                  <h3>Bikes</h3>
                </div>
              </a>
            </div>
            <div class="col-md-4">
              <a href="/search?utf8=✓&search=book&location=" class="destination-entry img" style="background-image: url('/assets/books.jpg');">
                <div class="text text-center">
                  <h3>Books</h3>
                </div>
              </a>
            </div>
            <div class="col-md-4">
              <a href="/search?utf8=✓&search=supplies&location=" class="destination-entry img" style="background-image: url('/assets/supplies.jpg');">
                <div class="text text-center">
                  <h3>Supplies</h3>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_search_bar.html.erb
<section class="ftco-section justify-content-end ftco-search">
  <div class="container-wrap ml-auto">
    <div class="row no-gutters">
      <div class="col-md-12 nav-link-wrap">
        <div class="nav nav-pills justify-content-center text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link active" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Borrow</a>
        </div>
      </div>
      <div class="col-md-12 tab-wrap">

        <div class="tab-content p-4 px-5" id="v-pills-tabContent">

          <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
            <%= form_tag(search_path, :method => "get", :class =>"search-destination") do %>
              <div class="row">
                <div class="col-md align-items-end">
                  <div class="form-group">
                    <label for="#">Borrow</label>
                    <%= search_field_tag :search, params[:search], placeholder: "Search for anything...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md align-items-end">
                  <div class="form-group">
                    <label for="#">Where</label>
                    <%= search_field_tag :location, params[:location], placeholder: "Where", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md align-self-end">
                  <div class="form-group">
                    <div class="form-field">
                      <input type="submit" value="Search" class="form-control btn btn-primary">
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_single_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <%= link_to "LendLord", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% @person = Person.find_by_user_id(current_user.id) %>

          <li class="nav-item"><%= link_to "Welcome, " + @person.username + "!", personal_home_index_path, class:"nav-link"%></li>
          <li class="nav-item"><%= link_to "My Profile", personal_home_index_path, class:"nav-link"%></li>
          <li class="nav-item"><%= link_to "Friends", friends_path, class:"nav-link"%></li>
          <% if current_user.person.username == "admin" %>
            <li class="nav-item"><%= link_to "User Items", items_path, class:"nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "My Items", user_items_path, class:"nav-link" %></li>
          <% end %>
          <li class="nav-item"><%= link_to "Transactions", transactions_path, class:"nav-link"%></li>
          <li class="nav-item"> <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-link"%></li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%></li>
          <li class="nav-item"><%= link_to "Log In", new_user_session_path, class:"nav-link"%></li>
        <% end %>
        <li class="nav-item"><%= link_to "Lend", new_item_path, class:"nav-link"%></li>

      </ul>
    </div>
  </div>
</nav>

<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/jquery-migrate-3.0.1.min.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery.easing.1.3.js"></script>
<script src="/assets/js/jquery.waypoints.min.js"></script>
<script src="/assets/js/jquery.stellar.min.js"></script>
<script src="/assets/js/owl.carousel.min.js"></script>
<script src="/assets/js/jquery.magnific-popup.min.js"></script>
<script src="/assets/js/aos.js"></script>
<script src="/assets/js/jquery.animateNumber.min.js"></script>
<script src="/assets/js/bootstrap-datepicker.js"></script>
<script src="/assets/js/scrollax.min.js"></script>
<script src="/assets/js/google-map.js"></script>
<script src="/assets/js/main.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Lendlord</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag "/assets/icomoon.css" %>

        <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Abril%20Fatface" %>


        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    </head>

    <body>

    <section style="z-index: 9999 !important; position:fixed; top: 5%; left: 30%;right: 30%;">
        <div class="container">
            <% flash.each do |message_type, message| %>
                <div id="hideMe" class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
        </div>
    </section>

    <%= yield %>

    </body>
</html>